joystick_relay:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min  : 0.5
      linear_forward_max  : 2.0
      linear_backward_min : 0.5
      linear_backward_max : 2.0
      angular_min : 0.7
      angular_max : 2.5
      steps       : 3